import CP2077ArchiveCore
import Foundation
import Testing

@Test func recordingThenRemovingDeletesExactlyWhatWasRecorded() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    try Data("generated by archive-loader".utf8).write(to: ours)

    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])

    var removed: [URL] = []
    let result = try ledger.removeRecorded(onRemoved: { removed.append($0) })

    #expect(result.map(\.lastPathComponent) == ["basegame_99_archive_loader.archive"])
    #expect(removed.count == 1)
    #expect(!FileManager.default.fileExists(atPath: ours.path))
}

@Test func aForeignLooseArchiveIsNeverDeleted() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    let theirs = game.contentDirectory.appending(path: "basegame_99_usermod.archive")
    try Data("generated by archive-loader".utf8).write(to: ours)
    try Data("a mod the user installed by hand".utf8).write(to: theirs)

    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])
    _ = try ledger.removeRecorded()

    // basegame_99_ is the documented way to hand-install a new-content mod, so
    // sweeping the prefix would destroy files the user owns.
    #expect(FileManager.default.fileExists(atPath: theirs.path))
    #expect(!FileManager.default.fileExists(atPath: ours.path))
}

@Test func aRecordedPathWhoseBytesChangedIsSkippedNotDeleted() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    try Data("generated by archive-loader".utf8).write(to: ours)

    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])
    try Data("something else entirely".utf8).write(to: ours)

    var skipped: [(URL, String)] = []
    let removed = try ledger.removeRecorded(onSkipped: { skipped.append(($0, $1)) })

    #expect(removed.isEmpty)
    #expect(skipped.count == 1)
    #expect(FileManager.default.fileExists(atPath: ours.path))
}

@Test func aRecordedPathThatIsAlreadyGoneIsNotAnError() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    try Data("generated".utf8).write(to: ours)
    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])
    try FileManager.default.removeItem(at: ours)

    let removed = try ledger.removeRecorded()

    #expect(removed.isEmpty)
}

@Test func removingClearsTheLedgerSoASecondSweepIsANoOp() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    try Data("generated".utf8).write(to: ours)
    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])

    _ = try ledger.removeRecorded()

    #expect(try ledger.recorded()?.artifacts.isEmpty ?? true)
    #expect(try ledger.removeRecorded().isEmpty)
}

@Test func recordingIsRelativeToTheGameRootSoAMovedInstallStillCleansUp() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let ours = game.install.managedLooseArchive
    try Data("generated by archive-loader".utf8).write(to: ours)

    let ledger = ArtifactLedger(game: game.install)
    try ledger.record([ours])

    let recorded = try #require(try ledger.recorded())
    #expect(recorded.artifacts.map(\.path)
        == ["archive/Mac/content/basegame_99_archive_loader.archive"])
}

@Test func noLedgerMeansNothingToRemove() throws {
    let game = try TestGame()
    defer { game.cleanUp() }

    #expect(try ArtifactLedger(game: game.install).recorded() == nil)
    #expect(try ArtifactLedger(game: game.install).removeRecorded().isEmpty)
}

@Test func recordingAnArtifactOutsideTheGameRootIsRefused() throws {
    let game = try TestGame()
    defer { game.cleanUp() }
    let outside = game.root.appending(path: "foreign.archive")
    try Data("not ours".utf8).write(to: outside)

    let ledger = ArtifactLedger(game: game.install)

    #expect(throws: Error.self) {
        try ledger.record([outside])
    }
    #expect(try ledger.recorded() == nil)
}
